name: Lint

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: 7

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install
              shell: bash

            - name: Setup Biome
              uses: biomejs/setup-biome@v1
              with:
                  version: 1.2.2

            - name: Run Biome
              run: biome ci .
